---
apiVersion: v1
kind: Namespace
metadata:
  name: busybox

---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: busybox
spec:
  volumes:
    - name: pv01
      persistentVolumeClaim:
        claimName: pvc01
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /mnt/data
        name: pv01
  restartPolicy: Always

