---
apiVersion: v1
kind: Namespace
metadata:
  name: coffee-pv

---
apiVersion: v1
kind: Service
metadata:
  name: coffee-pv-svc
  namespace: coffee-pv
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: coffee-pv

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coffee-pv
  namespace: coffee-pv
spec:
  replicas: 2
  serviceName: coffee-pv-svc
  selector:
    matchLabels:
      app: coffee-pv
  template:
    metadata:
      labels:
        app: coffee-pv
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: coffee-pv
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: www
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes:
          - "ReadWriteOnce"
        storageClassName: "nfs-client"
        # storageClassName: "gp2"
        resources:
          requests:
            storage: 1Gi
