---
apiVersion: v1
kind: Pod
metadata:
  name: curlutils
spec:
  containers:
  - name: curlutils
    image: curlimages/curl
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
